### ISSUE TITLE
is there a support to determine whether the network connection changed?

### ISSUE THREAD

**Issue by subhranshudas** [sindresorhus/is-online#49] opened 2018-06-11 01:35 UTC
Hi,
Is there any support to test whether the network connection changed.

Lets say i am connected to a wired connection and change my connection to wifi. Is there a way to detect it.

I know Chrome has `navigator.connection.onchange` but is there a cross browser and platform (mobile browsers) solution ?

Thanks.

**Comment by sindresorhus** [comment] 2018-06-11 03:44
Duplicate of #41

**Comment by sindresorhus** [comment] 2018-06-11 03:45
Browsers have APIs for this, but harder to do in Node.js as we would have to use NAPI to interact with the system APIs for each system. Something that is outside the scope of this module.

**Closed by sindresorhus** 2018-06-11 03:44 UTC

**Comment by subhranshudas** [comment] 2018-06-11 16:58
@sindresorhus thanks for the reply. Few follow up questions -

> Browsers have APIs for this, but harder to do in Node.js as we would have to use NAPI to interact with the system APIs for each system. Something that is outside the scope of this module.

i want to actually use this in browser, not sure when you say browsers have APIs, coz only in Chrome 61+ the navigator.connection is available, but not other browsers. Is there actually a browser API we can use.

And as per https://github.com/sindresorhus/is-online/issues/41 my requirement is to check when the network changes, online/offline is already supported by addEventListener('online/offline').

**Comment by sindresorhus** [comment] 2018-06-11 18:21
There's a polyfill: http://mattsnider.com/network-information-api-polyfill/

**Comment by subhranshudas** [comment] 2018-06-11 18:54
@sindresorhus thank you for the link. Again i might be horribly wrong, but the polyfill doesn't provide a mechanism to listen to network change event if the `connection.onchange` is not supported. It simply provides empty object as a safety net. This net i already have, but needed to find any browser API/library that supports the non-compatible browsers.

Thanks again!
