### ISSUE TITLE
npm tarball missing index.js for version 5.1.0

### ISSUE THREAD

**Issue by npow** [sindresorhus/is-online#24] opened 2016-02-17 19:55 UTC
When I npm install version 5.1.0, it is missing the `index.js` file. The file is there in version 5.0.1

```
➜  tmp  npm install is-online@5.1.0                                                                                                                                          [19:52:17]
is-online@5.1.0 node_modules/is-online
├── onetime@1.1.0
├── random-item@1.0.0
├── root-hints@1.0.8
└── is-reachable@1.3.0 (arrify@1.0.1, is-port-reachable@1.0.0, router-ips@0.2.0, each-async@1.1.1, url-parse-lax@1.0.0)
➜  tmp  ls node_modules/is-online                                                                                                                                            [19:52:20]
browser.js    hostnames.js  license       node_modules/ package.json  readme.md
```

```
➜  tmp  npm install is-online@5.0.1                                                                                                                                          [19:51:39]
is-online@5.0.1 node_modules/is-online
├── onetime@1.1.0
├── random-item@1.0.0
├── root-hints@1.0.8
└── is-reachable@1.3.0 (is-port-reachable@1.0.0, arrify@1.0.1, router-ips@0.2.0, each-async@1.1.1, url-parse-lax@1.0.0)
➜  tmp  ls node_modules/is-online                                                                                                                                            [19:51:51]
browser.js    hostnames.js  index.js      license       node_modules/ package.json  readme.md
```

**Comment by sindresorhus** [comment] 2016-02-17 20:02
Duplicate of #24.

**Closed by sindresorhus** 2016-02-17 20:02 UTC
